### ISSUE TITLE
statement_start_offset

### ISSUE THREAD

**Issue by uniqalex** [MicrosoftDocs/sql-docs.ru-ru#47]
Hello.
I want to discuss  about statement_start_offset. Doc article says that it is number of characters, but in example D this parameter is devided by 2. 
If we talking about "number of characters" - it does no matter how many bytes is used for storing 1 character, coz we set NUMBER OF CHARACTERS! Not a number of bytes.
Can you explain me, what i cant understand this article moment?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 785e6be1-0c51-7690-1eb6-c4c98c7c1133
* Version Independent ID: 79592f3b-ccff-06bd-eed8-08ab1bf74205
* Content: [sys.dm_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #1947](https://github.com/MicrosoftDocs/sql-docs/issues/1947) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @uniqalex

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/1947

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
