### ISSUE TITLE
Ошибка на странице - неправильный перевод

### ISSUE THREAD

**Issue by ASamSam** [MicrosoftDocs/sql-docs.ru-ru#48]
текущий текст:
SYS_CHANGE_OPERATION	nchar(1)	Задает тип изменения:
U = блокировка обновления
Я = Вставка

Д.б.:
I = Вставка

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8f36b593-b1f9-c112-1e44-865d2a61ecd0
* Version Independent ID: 46a61905-4066-99f9-9f91-76d4ba512d59
* Content: [CHANGETABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/system-functions/changetable-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-functions/changetable-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/system-functions/changetable-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by CeciAc** [comment]
Здравствуйте, @ASamSam  
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @ASamSam
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/sql/relational-databases/system-functions/changetable-transact-sql?view=sql-server-2017 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
