### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Levsha1337** [MicrosoftDocs/sql-docs.ru-ru#51]
В первой таблице в графе serveradmin имеется опечатка:
...роли сервера &gt;&gt;&gt;serveradmi&lt;&lt;&lt; могут изменять параметры...
Т.е. отсутствует последняя буква.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 81b47032-2e86-a8fd-cdab-c362ccad8f7b
* Version Independent ID: d19b09f6-06a6-67f6-5284-0bad0f1d53c9
* Content: [Роли уровня сервера - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/security/authentication-access/server-level-roles?view=aps-pdw-2016#feedback)
* Content Source: [docs/relational-databases/security/authentication-access/server-level-roles.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/security/authentication-access/server-level-roles.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by Levsha1337** [comment]
In russian version of document you have misprint.

**Comment by CeciAc** [comment]
Здравствуйте, @Levsha1337 
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by lichasu** [comment]
Здравствуйте, @Levsha1337 !  
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их.   
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
