### ISSUE TITLE
Ошибка перевода

### ISSUE THREAD

**Issue by Alexeyvg** [MicrosoftDocs/sql-docs.ru-ru#53]
В тексте:
"Следующие типы ошибок обрабатываются блоком CATCH, если они возникают на том же самом уровне выполнения, что и конструкция TRY...CATCH." пропущено отрицание, следовало перевести как:  
"Следующие типы ошибок не обрабатываются блоком CATCH, если они возникают на том же самом уровне выполнения, что и конструкция TRY...CATCH." 
Это кардинально изменило смысл описания.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5733f776-615e-9e0e-7df2-8adacf4c3b09
* Version Independent ID: 2f6cc6e5-8479-87d1-de8d-9ac97551925d
* Content: [TRY...CATCH (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/t-sql/language-elements/try-catch-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/try-catch-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/t-sql/language-elements/try-catch-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @Alexeyvg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Alexeyvg
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/sql/t-sql/language-elements/try-catch-transact-sql?view=sql-server-2017#feedback 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
