### ISSUE TITLE
Опечатка в тексте

### ISSUE THREAD

**Issue by Lasidora** [MicrosoftDocs/sql-docs.ru-ru#55]
Раздел Аргументы, таблица datepart - сокращения. Сокращение для hour должно быть hh, а не чч.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a16b2e33-bcd1-2502-949f-de24d0f687b0
* Version Independent ID: 1dd3a1c6-957f-288a-c12d-02bedb92d6cc
* Content: [DATEADD (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/t-sql/functions/dateadd-transact-sql?view=sql-server-2017#arguments)
* Content Source: [docs/t-sql/functions/dateadd-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/t-sql/functions/dateadd-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @Lasidora
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Lasidora
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @Lasidora !  
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/sql/t-sql/functions/dateadd-transact-sql?view=sql-server-2017#arguments 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
