### ISSUE TITLE
Different case of letter

### ISSUE THREAD

**Issue by IgorProjects** [MicrosoftDocs/sql-docs.ru-ru#56]
Title and article: STEndpoint
Code sample: STEndPoint

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f568804a-7d09-883f-1dce-01c61cbe49a1
* Version Independent ID: a18d033f-976c-c1f2-d75a-c5cd9202be1a
* Content: [STEndpoint (тип данных geography) - SQL Server](https://docs.microsoft.com/ru-ru/sql/t-sql/spatial-geography/stendpoint-geography-data-type?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/spatial-geography/stendpoint-geography-data-type.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/t-sql/spatial-geography/stendpoint-geography-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by srvbpigh** [comment]
Hello, @IgorProjects
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2995](https://github.com/MicrosoftDocs/sql-docs/issues/2995) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2996](https://github.com/MicrosoftDocs/sql-docs/issues/2996) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @IgorProjects

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/2996

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
