### ISSUE TITLE
пробел

### ISSUE THREAD

**Issue by rule8** [MicrosoftDocs/sql-docs.ru-ru#58]
узел Средаи выберите - пропущен пробел.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 77570f46-1d8e-8133-4c8f-7d71ce94e8d5
* Version Independent ID: 1da16ef8-3596-5675-0753-4d81ff449dd7
* Content: [Открытие монитора активности (среда SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/performance-monitor/open-activity-monitor-sql-server-management-studio?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/performance-monitor/open-activity-monitor-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/performance-monitor/open-activity-monitor-sql-server-management-studio.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srvbpigh** [comment]
Hello, @rule8
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @rule8
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/sql/relational-databases/performance-monitor/open-activity-monitor-sql-server-management-studio?view=sql-server-2017#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
