### ISSUE TITLE
Ссылка на скачивание не работает

### ISSUE THREAD

**Issue by Real3L0** [MicrosoftDocs/sql-docs.ru-ru#60]
Ссылка на скачивание не работает

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Загрузка SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/ru-ru/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @Real3L0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MaximFrantsuzov** [comment]
Ссылка на скачивание SSMS не работает.

**Comment by MaximFrantsuzov** [comment]
https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017  с английской версии сайта качает

**Comment by MiceRus** [comment]
Почему через WSUS не обновляется? Сам WSUS выкачал это обновление. Оно утверждено для установки, но так ничего и не встало. Приходится руками качать и обновлять.

**Comment by CeciAc** [comment]
Здравствуйте, @Real3L0!
Спасибо за отзыв. 
Наши инженеры рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
