### ISSUE TITLE
HYPERVISOR

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/sql-docs.ru-ru#61]
Hello!
"HYPERVISOR = SQL Server is running inside a hypervisor, which implies a hardware-assisted virtualization. When the Hyper_V role is installed, the hypervisor hosts the OS, so an instance running on the host OS is running in the hypervisor." - my SQL Server 2019 that's running inside a virtual machine on a Hyper-V host displays "HYPERVISOR" while the description above states the "HYPERVISOR" should be displayed only for SQL Server instances installed on the Hyper-V hosts themselves (not inside virtual machines!)...- is that correct? 
By the way, it's not clear which value must be displayed here for the virtual_machine_type/virtual_machine_type_desc field in case SQL Server is running inside the general Hyper-V based virtual machines.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c1073200-d5d6-a64e-d8d8-a4809873822b
* Version Independent ID: aab7789b-e333-2d9a-bfb9-52106184c156
* Content: [sys.dm_os_sys_info (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-sys-info-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @MichaelFirsov
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MichaelFirsov

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/3151

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
