### ISSUE TITLE
Ошибка в описании продукта

### ISSUE THREAD

**Issue by Alexeyvg** [MicrosoftDocs/sql-docs.ru-ru#66]
Описание "Использование диспетчера конфигурации SQL Server", пункт "Запуск диспетчера конфигурации SQL Server" не соответствует поведению продукта SQL Server 2016.  В меню "Пуск" в "Microsoft SQL Server", нет пунктов "Средства настройки" или "Диспетчер конфигурации"
Я запускал диспетчер конфигурации SQL Server запуском SQLServerManager13.msc, для SQL Server 2016.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: dbf3b54c-3a10-4e01-02d8-debc0a14da2e
* Version Independent ID: 4efa0d4f-9227-70d1-9745-8d32fef60c5a
* Content: [Управление службами компонента Database Engine - SQL Server](https://docs.microsoft.com/ru-RU/sql/database-engine/configure-windows/manage-the-database-engine-services?view=sql-server-2016#using-sql-server-configuration-manager)
* Content Source: [docs/database-engine/configure-windows/manage-the-database-engine-services.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/database-engine/configure-windows/manage-the-database-engine-services.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @Alexeyvg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @Alexeyvg!   

Спасибо за отзыв.  

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-RU/sql/database-engine/configure-windows/manage-the-database-engine-services?view=sql-server-2016#using-sql-server-configuration-manager.   

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
