### ISSUE TITLE
Case: the node hosting the mssql-server container has failed

### ISSUE THREAD

**Issue by ZenitChampion** [MicrosoftDocs/sql-docs.ru-ru#73]
You've set up 

kind: PersistentVolumeClaim
with
spec:
  accessModes:
  - ReadWriteOnce

Will this case be handled by k8s correctly?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Развертывание контейнера SQL Server с помощью служб Azure Kubernetes (AKS) - SQL Server](https://docs.microsoft.com/ru-ru/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @ZenitChampion
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ZenitChampion 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
