### ISSUE TITLE
Значение по умолчанию или привязка

### ISSUE THREAD

**Issue by Bagunda** [MicrosoftDocs/sql-docs.ru-ru#76]
В поле "Значение по умолчанию или привязка" у меня нет раскрывающегося списка.
По справке я не смог понять что надо вписать, чтобы штамп времени отпечатывался автоматически.
![2020-04-02_18-35-55](https://user-images.githubusercontent.com/16766521/78268469-e4656c00-7510-11ea-9e32-91dcfeca8226.png)

[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 69f06639-7bc3-2fe3-b544-c1dd8407e055
* Version Independent ID: ce44a2a8-d69d-8e4e-ff94-bb622be1a90e
* Content: [Свойства столбца таблицы (среда SQL Server Management Studio) - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/tables/table-column-properties-sql-server-management-studio?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DRU-RU%26k%3Dk(vdtsql.chm%3A65558)%26rd%3Dtrue&view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/table-column-properties-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/tables/table-column-properties-sql-server-management-studio.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @Bagunda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Bagunda 

 
Благодарим Вас за вклад. Да, этот отзыв связан с продуктом. Отправьте свое предложение, нажав кнопку "Отправить отзыв по продукту" в нижней части страницы документации. 

Если вы хотите поделиться своим мнением о документации, отправьте его по этому каналу. 

Благодарим за Ваш вклад в улучшение наших статей. 

Международная команда поддержки документации Microsoft
