### ISSUE TITLE
SQL Server

### ISSUE THREAD

**Issue by city22111** [MicrosoftDocs/sql-docs.ru-ru#82]
Ливневые стоки, отводимые с крыш зданий, вызывают подтапливание фундамента, участка, дорожных покрытий и насаждений. Компания «Сити Проект» предлагает заказать ливневые очистные сооружения из стеклопластика, обустроить дождевую канализацию, разработать блочные и модульные системы водоотведения и водоочистки поверхностного стока по выгодной цене.

Стеклопластик обеспечивает долговечность, надежность, практичность системы в процессе эксплуатации. Подготовка проекта и производство очистных сооружений ливневой канализации в стеклопластиковом корпусе. Очистка ливневого (дождевого) стока вод производительностью до 130 л/с.  https://www.cityprogect.ru/livnevye-ochistnye-sooruzheniya.html

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 48cb4a50-bcd6-38bc-187b-27cc36576219
* Version Independent ID: 38c1d92e-25d6-6237-9a04-6ca13bbb1a09
* Content: [Новые возможности в SQL Server 2019 - SQL Server](https://docs.microsoft.com/ru-ru/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/sql-server/what-s-new-in-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by city22111** [comment]
https://www.cityprogect.ru/livnevye-ochistnye-sooruzheniya.html

**Comment by srvbpigh** [comment]
Hello, @city22111
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @city22111 

Ваши комментарии нарушают наши правила поведения: https://opensource.microsoft.com/codeofconduct/.   

По этой причине Ваша заявка заблокирована и закрыта.  

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт
