### ISSUE TITLE
https://www.cityprogect.ru/livnevye-ochistnye-sooruzheniya.html

### ISSUE THREAD

**Issue by city22111** [MicrosoftDocs/sql-docs.ru-ru#83]
Вы также можете оставить отзыв непосредственно на GitHub 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 48cb4a50-bcd6-38bc-187b-27cc36576219
* Version Independent ID: 38c1d92e-25d6-6237-9a04-6ca13bbb1a09
* Content: [Новые возможности в SQL Server 2019 - SQL Server](https://docs.microsoft.com/ru-ru/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/what-s-new-in-sql-server-ver15.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/sql-server/what-s-new-in-sql-server-ver15.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @city22111
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @city22111 

Благодарим Вас за предоставленный комментарий. Комментарии помогают нам постоянно улучшать портал docs.microsoft.com. Однако нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий? 

С уважением, 

Международная команда Microsoft DOCS

**Comment by CeciAc** [comment]
Здравствуйте, @city22111 

Еще раз благодарим Вас за предоставленный комментарий. 

К сожалению, у нас по-прежнему недостаточно данных для обработки Вашего отзыва. Пока что мы закрываем этот вопрос на GitHub, но надеемся получать от Вас подробные отзывы в будущем. 

С уважением, 

Международная команда Microsoft DOCS
