### ISSUE TITLE
It seems to me that example don't work in MSSQL-2019 

### ISSUE THREAD

**Issue by OneLonelly** [MicrosoftDocs/sql-docs.ru-ru#85]
The "CREATE ASSEMBLY HelloWorld   
FROM &lt;system_drive&gt;:\Program Fi... " don't really work cause file name have to be quoted like string constant (on nvarchar-type variable). And   the next "CREATE ASSEMBLY ... FROM 0x4D5A900000000000 ... "  don't work cause new (since 2017) security politic.  Correct me if I wrong.  

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7bc10b70-11b5-a892-da24-fe25fa86c8c2
* Version Independent ID: 9c95ecb5-175c-d8e7-22d3-a81f1f58f6c3
* Content: [CREATE ASSEMBLY (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/t-sql/statements/create-assembly-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-assembly-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/t-sql/statements/create-assembly-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by srvbpigh** [comment]
Hello, @OneLonelly
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CarlRabeler** [comment]
@OneLonelly Thanks for the feedback. Fixing the first issue. Could be please elaborate on the second issue? Thank you.
Carl

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #4841](https://github.com/MicrosoftDocs/sql-docs/issues/4841) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @OneLonelly, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs/issues/4841. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
